#from kafka git

version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  producer:
    build: kafka-producer/
    container_name: producer-kafka
    ports:
      - "8190:8190"
    environment:
      KAFKA_SERVER: http://kafka:9092
      KAFKA_PRODUCER_ID: producerService
      FIRST_TOPIC_NAME: orders
      SECOND_TOPIC_NAME: batch
    depends_on:
      - kafka

  consumer:
    build: kafka-listener/
    container_name: consumer-kafka
    ports:
      - "8090:8090"
    environment:
      GROUP_ID:
      KAFKA_SERVER: http://kafka:9092
      FIRST_TOPIC_NAME: orders
      SECOND_TOPIC_NAME: batch
    depends_on:
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local